### PR TITLE
Add simple-json

### PR DESCRIPTION
**Pull request by alvivi**
This is an ongoing effort to make `purescript-simple-json` works. Not finished yet and not sure if this should be here 🤷‍♂

### CODE REVIEW

**Comment by alvivi** [comment]
I think that marshaling is working fine. The problem comes when doing unmarshal. Here is the example program that I'm using:

```purescript
module Main where

import Prelude

import Effect (Effect)
import Effect.Class.Console (log)
import Simple.JSON as JSON

main :: Effect Unit
main = do
  log "WRITE"
  log $ JSON.writeJSON true
  log $ JSON.writeJSON false
  log $ JSON.writeJSON (9001 :: Int)
  log $ JSON.writeJSON 9001.9001
  log $ JSON.writeJSON "yeah"
  log $ JSON.writeJSON [1,2,3,4]
  log $ JSON.writeJSON {foo: "bar", list: [1,2,3], nested: {wow: 9001}}

  log "READ"
  log $ show (JSON.readJSON "true" :: JSON.E Boolean)
  log $ show (JSON.readJSON "wow" :: JSON.E Boolean)
  log $ show (JSON.readJSON "false" :: JSON.E Boolean)
  log $ show (JSON.readJSON "9001" :: JSON.E Int)
  log $ show (JSON.readJSON "9001.9001" :: JSON.E Int)
  log $ show (JSON.readJSON "9001.9001" :: JSON.E Number)
  log $ show (JSON.readJSON "\"yeah\"" :: JSON.E String)
  log $ show (JSON.readJSON "[true, false, true]" :: JSON.E (Array Int))
  {--log $ show (JSON.readJSON "{\"foo\":\"bar\"}" :: JSON.E {foo :: String})--}

```

As said, marshaling works fine. Unmarshaling records is not implemented, neither null nor undefined values.

The current problem is parsing `[true, false, true]` as `Array Int`. Right now the program is printing `Right []` when an error is expected. Based on [simple-json implementation](https://github.com/justinwoo/purescript-simple-json/blob/master/src/Simple/JSON.purs#L171) seems that there is some error when dealing with arrays in the runtime or one unsafe functions 🤷‍♂

**Comment by alvivi** [comment]
Mmmm... 🤔 The proper value is carried until `PS__traverseWithIndexDefault`. After that the array is empty. Maybe the error is in `foldable-traversable`.

**Comment by andyarvanitis** [comment]
Cool, I'll review your changes as soon as I can. As for the potential error in `foldable-traversable`, let me know if you spot anything. Its tests pass, but that doesn't mean something wasn't wrong.

**Comment by andyarvanitis** [comment]
Also, I just updated the README in this repo with a description of the coding conventions I've been following, which might have seemed a bit strange to you (including the trailing underscore on parameter names). Don't feel you need to go back and change your code to conform to it, but I might normalize the code in the future (maybe after any other conventions evolve).

**Comment by alvivi** [comment]
@andyarvanitis, seems that the problem is here:
https://github.com/andyarvanitis/purescript-native-go-ffi/blob/master/purescript-foldable-traversable/FunctorWithIndex.go#L12
if instead of using `xs, _ := xs_.([]Any)` I use `xs, _ := xs_.([]interface{})` parsing works. Mmmm... 🤔 I think that the use of `Any` is going to cause lots of troubles when doing ffi because is not an alias for `interface{}`.

**Comment by andyarvanitis** [comment]
Ah, that is in fact a typo. `Any` was supposed to be an alias, like the other types defined there. I probably removed the `=` at some point to try something and forgot to put it back. I'll fix it tonight and re-test. Thanks for catching it

https://github.com/andyarvanitis/purescript-native/issues/39

**Comment by alvivi** [comment]
Perfect! that also should fix all the code that I tagged with a note here. I keep an eye on that issue and then continue with this.

**Comment by andyarvanitis** [comment]
Ok, fixed the runtime in https://github.com/purescript-native/go-runtime/commit/5a52a127a14ab8e4227e685aa18615b07d9b4b73 (no updates to the compiler itself needed). The compiler tests all pass without issue, which I would expect with that change. 

If you're still seeing problems, make sure that your `go.mod` doesn't specify a specific version/commit of the runtime. Let me know how it goes and we can merge your changes when you're ready.

**Comment by alvivi** [comment]
Everything working @andyarvanitis! Ready to review. There are some differences between `simple-json` here and in Javascript (https://github.com/justinwoo/purescript-simple-json/issues/65) but erlang implementation is doing the same, so I guess that's ok.

**Comment by andyarvanitis** [comment]
Looks good!

**Comment by andyarvanitis** [comment]
@alvivi Were you able to run the test suite of `simple-json`? I just tried it in order to test something else, and noticed it failed on at least one case.

**Comment by alvivi** [comment]
@andyarvanitis How do you run tests with `psgo`? I just cloned `simple-json` project, run `spago init` and `spago build -- -g corefn`. Then I run `psgo --tests` but it seems that the command runs into an infinite loop (compiling, show purs warnings, building go files, compiling, show purs warnings...)

**Comment by andyarvanitis** [comment]
@alvivi `psgo --tests` is actually for running the compiler test suite, not a particular package/module test suite (so you saw it running all of those). At some point it might be easy to use `spago` to run a program's tests, but for now I just copy everything from the package's `test` directory into *working-dir*`/src`, and change the module name in `Main.purs` from `module Test.Main` to `module Main`, and then build and run it like any other program using psgo. 

edit: I will bump up the priority of making this easier to do, via spago or otherwise

**Comment by i-am-the-slime** [comment]
I get this:
```
/Users/mark/code/psgotest/output/Main/Main.go
panic: Foreign value 'isArray' for purescript module 'Foreign' not found
```
Although I see this function.

**Comment by i-am-the-slime** [comment]
One hour to notice that I was just missing transitive dependencies... 😞

**Comment by andyarvanitis** [comment]
@i-am-the-slime Sorry to hear that. Do you think it's anything the tooling should have been able to catch?

**Comment by i-am-the-slime** [comment]
@andyarvanitis  I think in the end an explanation of how to add custom ffi (maybe your own as well) would have prevented this.

**Pull request merged**
